'use strict';
const icons={home:'M3 10l9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V10 M9 21v-8h6v8',wallet:'M20 8V5a2 2 0 0 0-2-2H5a3 3 0 0 0 0 6h15v11H5a3 3 0 0 1-3-3V6 M20 12h-5v5h5 M16 14.5h.1',sparkles:'M12 3l2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z M20 2v4 M18 4h4',package:'M3 7l9-5 9 5v10l-9 5-9-5z M3 7l9 5 9-5 M12 12v10 M7.5 4.5l9 5',clipboard:'M9 4H5v17h14V4h-4 M9 2h6v5H9z M8 12h8 M8 16h6',users:'M16 21v-3a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v3 M9 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M20 21v-3a4 4 0 0 0-3-3.87 M16 2.13a4 4 0 0 1 0 7.75',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8z',sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v2 M12 20v2 M2 12h2 M20 12h2 M5 5l1.5 1.5 M17.5 17.5L19 19 M5 19l1.5-1.5 M17.5 6.5L19 5',chevron:'M6 9l6 6 6-6',pointer:'M4 3l6 18 3-7 7-3z',activity:'M2 12h4l3-9 5 18 3-9h5',close:'M6 6l12 12 M6 18L18 6',check:'M5 12l4 4L19 6',plus:'M12 5v14 M5 12h14',left:'M15 6l-6 6 6 6',right:'M9 6l6 6-6 6',clock:'M12 8v5l3 2 M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20',swap:'M3 7h18l-4-4 M21 17H3l4 4'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[n]||icons.home}"/></svg>`;
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const avatar=id=>{const p=HZ.person(id);return `<span class="avatar" style="--avatar-color:${p.color};--avatar-bg:${p.bg}">${p.initial}</span>`};
const yuan=c=>'¥'+HZ.money(c);
let page='home',formState=null,filter='pending',week=0,toastTimer;
const modules={bills:{title:'共享账单',location:'玄关 · 把钱算清',icon:'wallet',color:'purple'},cleaning:{title:'清洁值日',location:'客厅 · 把事分好',icon:'sparkles',color:'blue'},items:{title:'公共物品',location:'厨房 · 缺什么，一起补',icon:'package',color:'orange'},pacts:{title:'室友公约',location:'公告墙 · 好好商量，安心同住',icon:'clipboard',color:'green'}};
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3000)}
function refreshIcons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon))}
function act(fn,message){try{fn();if(message)toast(message);if(HZ.storageFailed)toast('浏览器未允许保存，本次操作只在当前页面有效');}catch(e){toast(e.message)}}
function renderHome(){
  const state=HZ.state,me=HZ.me(),s=HZ.summary(),low=state.items.filter(i=>i.status!=='full'),unconfirmed=state.pacts.filter(p=>!p.confirmed.includes(me.id));
  $('greeting-name').textContent=me.name;$('date-label').textContent=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Singapore',month:'long',day:'numeric',weekday:'long'}).format(new Date()).replace('星期','周').toUpperCase();
  $('identity-select').innerHTML=HZ.people.map(p=>`<option value="${p.id}" ${p.id===me.id?'selected':''}>${p.name} · ${p.room}室</option>`).join('');
  $('top-avatar').textContent=me.initial;$('top-avatar').style.cssText=`--avatar-color:${me.color};--avatar-bg:${me.bg}`;
  $('drawer-identity-select').innerHTML=$('identity-select').innerHTML;$('drawer-avatar').textContent=me.initial;$('drawer-avatar').style.cssText=`--avatar-color:${me.color};--avatar-bg:${me.bg}`;
  $('summary').innerHTML=[['bills','wallet','purple','我待付的费用',yuan(s.owed),'','打开账单'],['bills','wallet','blue','我垫付待收回',yuan(s.receivable),'','查看进度'],['cleaning','sparkles','orange','本周我的值日',s.tasks,'项','查看排班']].map(([p,i,c,label,value,unit,hint])=>`<button class="summary-card" data-open="${p}"><span class="metric-icon ${c}">${icon(i)}</span><span><span class="metric-label">${label}</span><span class="metric-number">${value}<small>${unit}</small></span></span><span class="metric-aside">${hint}</span></button>`).join('');
  $('bill-count').textContent=state.bills.filter(b=>b.shares.some(s=>s.personId===me.id&&!s.paid)).length||'';$('item-count').textContent=low.length||'';
  document.querySelectorAll('[data-avatar]').forEach(el=>{const p=HZ.person(el.dataset.avatar);el.textContent=p.initial;el.style.cssText=`--avatar-color:${p.color};--avatar-bg:${p.bg}`});
  document.querySelectorAll('.room').forEach(el=>{el.classList.toggle('selected',el.dataset.person===me.id);el.setAttribute('aria-label',`切换为${HZ.person(el.dataset.person).name}`)});
  $('roommate-buttons').innerHTML=HZ.people.map(p=>`<button class="roommate-button ${p.id===me.id?'active':''}" data-person="${p.id}">${avatar(p.id)}${p.name}${p.id===me.id?' · 我':''}</button>`).join('');
  $('kitchen-hint').textContent=low.length?low.length+'件物品需要补货':'物品都充足';$('kitchen-badge').textContent=low.length||'';
  $('living-hint').textContent=s.tasks?s.tasks+'项值日等你处理':'看看本周排班';$('entry-hint').textContent=s.owed?'待付 '+yuan(s.owed):'我的费用已结清';$('board-hint').textContent=unconfirmed.length?unconfirmed.length+'条公约待你确认':'公约都已确认';
  const todos=[];
  if(s.owed)todos.push({page:'bills',title:'还有费用需要结清',desc:'你的待付款合计 '+yuan(s.owed),tag:'待结清'});
  const myTasks=state.tasks.filter(t=>t.owner===me.id&&!t.done&&t.due<=HZ.addDays(HZ.monday,6));if(myTasks.length)todos.push({page:'cleaning',title:myTasks[0].area+'轮到你值日',desc:(myTasks[0].due===HZ.today?'今天':myTasks[0].due.slice(5))+' · '+myTasks[0].detail,tag:'待完成'});
  const swaps=state.tasks.filter(t=>t.swap?.to===me.id);if(swaps.length)todos.push({page:'cleaning',title:'你有一条换班申请',desc:HZ.person(swaps[0].swap.from).name+'想请你接手'+swaps[0].area,tag:'待回应'});
  if(low.length)todos.push({page:'items',title:low.filter(i=>!i.claim).length?'家里有物品需要补货':'看看补货进度',desc:low.map(i=>i.name).join('、'),tag:low.filter(i=>!i.claim).length+'件待认领'});
  if(unconfirmed.length)todos.push({page:'pacts',title:'一起确认生活小约定',desc:unconfirmed[0].title+' · 等你确认',tag:'待确认'});
  $('todo-number').textContent=todos.length+'件小事';$('all-clear').hidden=!!todos.length;
  $('todo-list').innerHTML=todos.map(t=>{const m=modules[t.page];return `<button class="todo-row" data-open="${t.page}"><span class="todo-icon ${m.color}">${icon(m.icon)}</span><span><strong>${esc(t.title)}</strong><small>${esc(t.desc)}</small><span class="tag ${m.color}">${esc(t.tag)}</span></span></button>`}).join('');
  $('activity-list').innerHTML=state.events.slice(0,3).map(e=>`<div class="activity-row"><span class="activity-dot"></span><div><p>${esc(e.text)}</p><small>${new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Singapore',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(e.time))}</small></div></div>`).join('');
}
function openPanel(p){if(p==='home'){$('drawer').close();page='home';return}page=p;formState=null;filter='pending';week=0;renderPanel();if(!$('drawer').open)$('drawer').showModal()}
function renderPanel(){if(!modules[page])return;const m=modules[page];$('drawer-title').textContent=m.title;$('drawer-location').textContent=m.location;$('drawer-tabs').innerHTML=Object.entries(modules).map(([p,m])=>`<button class="drawer-tab ${p===page?'active':''}" data-open="${p}">${m.title}</button>`).join('');$('drawer-content').innerHTML=formState?renderForm():({bills:renderBills,cleaning:renderCleaning,items:renderItems,pacts:renderPacts}[page])();refreshIcons($('drawer'));bindPanelForms();}
function renderBills(){const bills=HZ.state.bills.filter(b=>filter==='all'||b.shares.some(s=>!s.paid));return `<p class="module-intro">每笔垫付都有记录，每个人的分摊都清楚。当前身份：${HZ.me().name}</p><div class="module-toolbar"><div class="filter-row"><button data-filter="pending" class="${filter==='pending'?'active':''}">未结清</button><button data-filter="all" class="${filter==='all'?'active':''}">全部账单</button></div><button class="primary" data-form="bill">${icon('plus')}记一笔</button></div>${bills.map(b=>{const share=b.shares.find(s=>s.personId===HZ.state.current),pending=b.shares.filter(s=>!s.paid);return `<article class="module-card"><div class="card-head"><div><h3>${esc(b.title)}</h3><p>${b.category} · ${HZ.person(b.payer).name}垫付 · ${b.date.slice(5)}</p></div><div class="amount">${yuan(b.total)}</div></div><div class="shares-list">${b.shares.map(s=>`<div class="share-row">${avatar(s.personId)}<span>${HZ.person(s.personId).name}${s.personId===HZ.state.current?'（我）':''}</span><span class="share-price">${yuan(s.cents)}</span><span class="status-pill ${s.paid?'ok':'warn'}">${s.personId===b.payer?'已垫付':s.paid?'已结清':'待结清'}</span></div>`).join('')}</div><div class="card-footer"><small>${pending.length?pending.length+'人待结清 · 待收 '+yuan(pending.reduce((s,x)=>s+x.cents,0)):'全员已结清'}</small>${share&&!share.paid?`<button class="primary" data-settle="${b.id}">我已支付 ${yuan(share.cents)}</button>`:b.payer===HZ.state.current&&pending.length?`<button class="soft-button" data-remind="${b.id}">提醒结清</button>`:'<span class="status-pill ok">'+(share?.paid?'我的部分已结清':'无需参与分摊')+'</span>'}</div></article>`}).join('')||empty('暂时没有未结清的账单')}`}
function renderCleaning(){const start=HZ.addDays(HZ.monday,week*7),end=HZ.addDays(start,6),tasks=HZ.state.tasks.filter(t=>t.due>=start&&t.due<=end).sort((a,b)=>a.due.localeCompare(b.due));return `<p class="module-intro">轮流分担，做完打卡。有事可以申请换班，等对方确认。</p><div class="module-toolbar"><div class="week-controls"><button class="icon-button" data-week="-1" aria-label="上一周">${icon('left')}</button><span>${start.slice(5)} — ${end.slice(5)}</span><button class="icon-button" data-week="1" aria-label="下一周">${icon('right')}</button></div><button class="primary" data-form="schedule">${icon('plus')}添加轮班</button></div>${tasks.map(t=>`<article class="module-card task-card ${t.done?'done':''}"><div class="card-head"><div><h3>${esc(t.area)}清洁</h3><p>${esc(t.detail)}</p></div><span class="status-pill ${t.done?'ok':t.due<HZ.today?'bad':'warn'}">${t.done?'已完成':t.due<HZ.today?'已逾期':t.due===HZ.today?'今天截止':t.due.slice(5)+' 截止'}</span></div><div class="task-person">${avatar(t.owner)}<span>${HZ.person(t.owner).name}${t.owner===HZ.state.current?'（我）':''}负责</span></div>${t.swap?`<div class="swap-box">${HZ.person(t.swap.from).name}申请由${HZ.person(t.swap.to).name}接手 · 等待确认${t.swap.to===HZ.state.current?`<div class="button-row"><button class="secondary" data-swap-reject="${t.id}">这次不方便</button><button class="primary" data-swap-accept="${t.id}">接受换班</button></div>`:t.swap.from===HZ.state.current?`<button class="text-button" data-swap-cancel="${t.id}">取消申请</button>`:''}</div>`:''}${!t.done&&t.owner===HZ.state.current&&!t.swap?`<div class="card-footer"><button class="secondary" data-swap="${t.id}">${icon('swap')}申请换班</button><button class="primary" data-complete="${t.id}">${icon('check')}我打扫好了</button></div>`:''}</article>`).join('')||empty('本周还没有排班，可以添加每周轮班。')}`}
function renderItems(){const needed=HZ.state.items.filter(i=>i.status!=='full').length;return `<p class="module-intro">快用完时标记一下，谁方便谁认领。买好后可直接生成AA账单。</p><div class="module-toolbar"><span class="status-pill warn">${needed}件需要补货</span><button class="primary" data-form="item">${icon('plus')}登记物品</button></div><div class="item-grid">${[...HZ.state.items].sort((a,b)=>({empty:0,low:1,full:2}[a.status]-{empty:0,low:1,full:2}[b.status])).map(i=>`<article class="module-card item-card"><span class="item-icon ${i.status==='full'?'blue':'orange'}">${icon('package')}</span><div class="card-head"><div><h3>${esc(i.name)}</h3><p>${esc(i.location)}</p></div><span class="status-pill ${i.status==='full'?'ok':i.status==='empty'?'bad':'warn'}">${{full:'充足',low:'快用完',empty:'已用完'}[i.status]}</span></div><p class="item-claim">${i.claim?HZ.person(i.claim).name+'已认领补货':'上次补货 '+i.last.slice(5)}</p><div class="item-actions">${i.claim===HZ.state.current?`<button class="primary" data-purchase="${i.id}">买好了</button><button class="text-button" data-unclaim="${i.id}">取消认领</button>`:i.claim?'<span class="status-pill">补货中</span>':`<select data-item-status="${i.id}" aria-label="${esc(i.name)}的状态">${['full','low','empty'].map(s=>`<option value="${s}" ${s===i.status?'selected':''}>${{full:'充足',low:'快用完',empty:'已用完'}[s]}</option>`).join('')}</select>${i.status!=='full'?`<button class="soft-button" data-claim="${i.id}">我来买</button>`:''}`}</div></article>`).join('')}</div>`}
function renderPacts(){return `<p class="module-intro">把生活习惯提前说清楚。每次修改后，都需要四位室友重新确认。</p><div class="module-toolbar"><span class="status-pill green">${HZ.state.pacts.filter(p=>p.confirmed.length===4).length}条已达成一致</span><button class="primary" data-form="pact">${icon('plus')}新增公约</button></div>${HZ.state.pacts.map(p=>`<article class="module-card"><div class="card-head"><div><h3>${esc(p.title)}</h3><p>第${p.version}版 · ${p.updated}更新</p></div><span class="status-pill ${p.confirmed.length===4?'ok':'warn'}">${p.confirmed.length}/4 已确认</span></div><p class="pact-content">${esc(p.content)}</p><div class="confirmation-people">${HZ.people.map(person=>`<span class="confirmation-person ${p.confirmed.includes(person.id)?'confirmed':''}">${avatar(person.id)}${person.name}${p.confirmed.includes(person.id)?icon('check'):''}</span>`).join('')}</div><div class="card-footer"><button class="text-button" data-edit-pact="${p.id}">修改公约</button>${p.confirmed.includes(HZ.state.current)?'<span class="status-pill ok">我已确认</span>':`<button class="primary" data-confirm-pact="${p.id}">同意并确认</button>`}</div>${p.history.length?`<details><summary>查看${p.history.length}次修改记录</summary>${p.history.map(h=>`<p>第${h.version}版 · ${h.updated}<br>${esc(h.content)}</p>`).join('')}</details>`:''}</article>`).join('')}`}
function empty(text){return `<div class="empty-state">${icon('check')}${text}</div>`}
const amountToCents=value=>{const s=String(value).trim();if(!/^\d+(\.\d{1,2})?$/.test(s))throw Error('金额最多支持两位小数');const [whole,decimal='']=s.split('.');const n=Number(whole)*100+Number(decimal.padEnd(2,'0'));if(!Number.isSafeInteger(n)||n<=0||n>100000000)throw Error('请输入0.01元至100万元之间的金额');return n};
const personOptions=(selected=HZ.state.current,exclude)=>HZ.people.filter(p=>p.id!==exclude).map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${p.name} · ${p.room}室</option>`).join('');
const peopleChoices=()=>`<div class="people-choices">${HZ.people.map(p=>`<label class="person-choice"><input type="checkbox" name="participants" value="${p.id}" checked>${avatar(p.id)}${p.name}</label>`).join('')}</div>`;
function renderForm(){
 const {name,id}=formState;let body='';
 if(name==='bill')body=`<h3>记一笔共享费用</h3><label class="field"><span>这笔钱花在哪？</span><input name="title" required maxlength="60" placeholder="例如：10月网费、公共洗衣液" autocomplete="off"></label><div class="field-grid"><label class="field"><span>总金额（元）</span><input name="total" type="number" step="0.01" min="0.01" max="1000000" required placeholder="0.00" inputmode="decimal"></label><label class="field"><span>费用类型</span><select name="category"><option>日用品</option><option>水电</option><option>房租</option><option>网费</option><option>其他</option></select></label></div><label class="field"><span>谁先垫付？</span><select name="payer">${personOptions()}</select></label><div class="field"><span>哪些室友参与分摊？</span>${peopleChoices()}<p class="field-hint">不参与的室友取消勾选，垫付人的部分会自动结清。</p></div><label class="field"><span>分摊方式</span><select name="splitMode"><option value="equal">平均分摊</option><option value="custom">自定义金额</option></select></label><div class="split-preview" id="split-preview">输入金额后，自动计算每人的分摊。</div><div class="form-error" id="form-error" role="alert"></div><div class="button-row"><button type="button" class="secondary" data-back-form>取消</button><button class="primary" type="submit">生成AA账单</button></div>`;
 if(name==='purchase'){const item=HZ.state.items.find(i=>i.id===id);body=`<h3>${esc(item.name)} · 买好了</h3><div class="inline-note">购买人：${HZ.me().name}。完成后物品恢复为「充足」，其他室友可以看到补货结果。</div><label class="field"><span>实际花了多少钱？（元）</span><input name="total" type="number" step="0.01" min="0.01" max="1000000" required placeholder="例如：36.00" inputmode="decimal"></label><label class="check-option"><input type="checkbox" name="makeBill" checked>同时生成AA账单</label><div class="field" id="purchase-participants"><span>哪些室友一起分摊？</span>${peopleChoices()}<div class="split-preview" id="split-preview">输入金额后，自动计算每人的分摊。</div></div><div class="form-error" id="form-error" role="alert"></div><div class="button-row"><button type="button" class="secondary" data-back-form>取消</button><button class="primary" type="submit">完成补货</button></div>`;}
 if(name==='item')body=`<h3>登记公共物品</h3><label class="field"><span>物品名称</span><input name="name" required maxlength="30" placeholder="例如：浴室纸巾"></label><label class="field"><span>放在哪里？</span><select name="location"><option>厨房</option><option>客厅</option><option>卫生间</option><option>阳台</option><option>玄关</option><option>公共区域</option></select></label><label class="field"><span>现在的状态</span><select name="status"><option value="full">充足</option><option value="low">快用完</option><option value="empty">已用完</option></select></label><div class="inline-note">标记「快用完」或「已用完」后，会自动出现在首页的补货待办里。</div><div class="form-error" id="form-error" role="alert"></div><div class="button-row"><button type="button" class="secondary" data-back-form>取消</button><button class="primary" type="submit">登记物品</button></div>`;
 if(name==='swap'){const task=HZ.state.tasks.find(t=>t.id===id);body=`<h3>申请换班 · ${esc(task.area)}</h3><div class="inline-note">${task.due}截止 · ${esc(task.detail)}<br>对方接受后，这次任务的负责人会更新为对方。后续轮班保持原计划。</div><label class="field"><span>想请哪位室友帮忙？</span><select name="target">${personOptions(undefined,HZ.state.current)}</select></label><div class="field-hint">提交后，可以切换为受邀室友，体验接受或婉拒换班。</div><div class="form-error" id="form-error" role="alert"></div><div class="button-row"><button type="button" class="secondary" data-back-form>取消</button><button class="primary" type="submit">发送换班申请</button></div>`;}
 if(name==='schedule')body=`<h3>添加每周轮班</h3><label class="field"><span>清洁区域</span><input name="area" required maxlength="20" placeholder="例如：阳台"></label><label class="field"><span>每周哪天完成？</span><select name="day">${['周一','周二','周三','周四','周五','周六','周日'].map((d,i)=>`<option value="${i}" ${i===5?'selected':''}>${d}</option>`).join('')}</select></label><div class="field"><span>参与轮班的室友</span>${peopleChoices()}</div><div class="inline-note">按照小林 → 阿泽 → 小夏 → 周周的顺序，为勾选的室友生成未来4周排班，从最近的指定星期开始。</div><div class="form-error" id="form-error" role="alert"></div><div class="button-row"><button type="button" class="secondary" data-back-form>取消</button><button class="primary" type="submit">生成4周排班</button></div>`;
 if(name==='pact'){const pact=id?HZ.state.pacts.find(p=>p.id===id):null;body=`<h3>${pact?'修改室友公约':'发起新的生活公约'}</h3>${!pact?`<label class="field"><span>可以从一个常见约定开始</span><select name="template" id="pact-template"><option value="">自己写一条</option><option value="quiet">安静时段</option><option value="guest">访客与留宿</option><option value="pet">宠物约定</option><option value="food">冰箱与食物</option></select></label>`:'<div class="inline-note">修改后会保留旧版本，四位室友需要重新确认。</div>'}<label class="field"><span>公约标题</span><input name="title" required maxlength="30" value="${esc(pact?.title||'')}" placeholder="例如：冰箱使用规则"></label><label class="field"><span>大家一起约定</span><textarea name="content" required maxlength="500" placeholder="写清楚你希望共同遵守的规则">${esc(pact?.content||'')}</textarea></label><div class="form-error" id="form-error" role="alert"></div><div class="button-row"><button type="button" class="secondary" data-back-form>取消</button><button class="primary" type="submit">${pact?'保存并重新确认':'发起共同确认'}</button></div>`;}
 return `<button class="back-button" data-back-form>${icon('left')}返回${modules[page].title}</button><form id="module-form" class="form-card" data-form-name="${name}">${body}</form>`;
}
function showForm(name,id){formState={name,id};renderPanel();$('drawer-content').scrollTop=0;$('module-form').querySelector('input:not([type="checkbox"]),select,textarea')?.focus()}
function updateSplitPreview(){const f=$('module-form'),el=$('split-preview');if(!f||!el)return;const data=new FormData(f),ids=data.getAll('participants');let total;try{total=amountToCents(data.get('total'))}catch{el.innerHTML='输入有效金额后，自动计算每人的分摊。';return}if(!ids.length){el.innerHTML='请至少勾选一位参与分摊的室友。';return}const custom=data.get('splitMode')==='custom';el.innerHTML=HZ.split(total,ids).map(s=>`<div class="share-row">${avatar(s.personId)}<span>${HZ.person(s.personId).name}</span><span class="share-price">${custom?`<input class="split-input" name="custom-${s.personId}" type="number" min="0" step="0.01" value="${HZ.money(s.cents).replace(/,/g,'')}" aria-label="${HZ.person(s.personId).name}的分摊金额"> 元`:yuan(s.cents)}</span></div>`).join('')+`<div class="field-hint">${custom?'自定义金额的合计需要等于总金额。':'金额按分精确计算，尾差由排在前面的室友承担。'}</div>`;}
function bindPanelForms(){const f=$('module-form');if(!f)return;const name=f.dataset.formName;f.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(f),id=formState.id;try{let operation,message;const ids=d.getAll('participants');if(name==='bill'){const total=amountToCents(d.get('total'));let custom;if(d.get('splitMode')==='custom'){custom={};for(const personId of ids){const raw=d.get('custom-'+personId);if(raw==='0'||raw==='0.00')custom[personId]=0;else custom[personId]=amountToCents(raw);}}operation=()=>HZ.actions.createBill({title:d.get('title'),total,payer:d.get('payer'),ids,category:d.get('category'),custom});message='AA账单已生成，每位室友的分摊已算好';}if(name==='purchase'){const total=amountToCents(d.get('total')),makeBill=d.has('makeBill');operation=()=>HZ.actions.purchaseItem(id,total,makeBill?ids:[HZ.state.current],makeBill);message=makeBill?'补货完成，AA账单已生成':'补货完成，物品已恢复充足';}if(name==='item'){operation=()=>HZ.actions.addItem({name:d.get('name'),location:d.get('location'),status:d.get('status')});message='物品已登记';}if(name==='swap'){operation=()=>HZ.actions.requestSwap(id,d.get('target'));message='换班申请已发出，等待对方确认';}if(name==='schedule'){operation=()=>HZ.actions.addSchedule({area:d.get('area'),day:Number(d.get('day')),ids});message='未来4周的轮班已安排';}if(name==='pact'){operation=()=>HZ.actions.editPact(id,{title:d.get('title'),content:d.get('content')});message=id?'公约已更新，等待全员重新确认':'新公约已发起，等待室友确认';}const prior=formState;formState=null;try{operation();toast(message);$('drawer-content').scrollTop=0;if(HZ.storageFailed)toast('当前浏览器未允许保存，请保持此页面打开');}catch(error){formState=prior;throw error}}catch(error){$('form-error').textContent=error.message;}});
 if(name==='bill'||name==='purchase'){updateSplitPreview();f.addEventListener('input',e=>{if(e.target.name==='total')updateSplitPreview()});f.addEventListener('change',e=>{if(['participants','splitMode'].includes(e.target.name))updateSplitPreview();if(e.target.name==='makeBill')$('purchase-participants').hidden=!e.target.checked;});}
 if(name==='pact'&&!formState.id)$('pact-template').addEventListener('change',e=>{const templates={quiet:['安静时段','晚上 23:00 至早上 8:00 保持安静，听音乐、打游戏戴耳机。'],guest:['访客与留宿','朋友来访提前告知；留宿需征得全体室友同意。'],pet:['宠物约定','养宠物前征得全体室友同意，主人负责清洁、看护，避免影响室友休息。'],food:['冰箱与食物','冰箱各自使用固定区域；使用室友的食物前先询问，每周清理一次过期食品。']};const v=templates[e.target.value];if(v){f.elements.title.value=v[0];f.elements.content.value=v[1];}});
}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.open){openPanel(d.open);return}if(d.person){formState=null;act(()=>HZ.actions.selectPerson(d.person),'现在以'+HZ.person(d.person).name+'的身份回家');return}if('backForm' in d){formState=null;renderPanel();return}if(d.form){showForm(d.form);return}if(d.purchase){showForm('purchase',d.purchase);return}if(d.swap){showForm('swap',d.swap);return}if(d.editPact){showForm('pact',d.editPact);return}if(d.filter){filter=d.filter;renderPanel();return}if(d.week){week+=Number(d.week);renderPanel();return}if(d.settle)act(()=>HZ.actions.settleBill(d.settle),'已记录结清');if(d.remind)act(()=>HZ.actions.remindBill(d.remind),'已在家的动态中提醒');if(d.complete)act(()=>HZ.actions.completeTask(d.complete),'打扫完成，辛苦啦！');if(d.claim)act(()=>HZ.actions.claimItem(d.claim),'补货已认领，其他室友会看到');if(d.unclaim)act(()=>HZ.actions.unclaimItem(d.unclaim),'已取消认领');if(d.confirmPact)act(()=>HZ.actions.confirmPact(d.confirmPact),'公约已确认');if(d.swapAccept)act(()=>HZ.actions.resolveSwap(d.swapAccept,true),'已接受换班，排班已更新');if(d.swapReject)act(()=>HZ.actions.resolveSwap(d.swapReject,false),'已回应这次申请');if(d.swapCancel)act(()=>HZ.actions.cancelSwap(d.swapCancel),'换班申请已取消');});
document.addEventListener('change',e=>{if(e.target.dataset.itemStatus)act(()=>HZ.actions.setItemStatus(e.target.dataset.itemStatus,e.target.value),'已更新物品状态')});
$('identity-select').addEventListener('change',e=>{formState=null;act(()=>HZ.actions.selectPerson(e.target.value),'身份已切换')});
$('drawer-identity-select').addEventListener('change',e=>{formState=null;act(()=>HZ.actions.selectPerson(e.target.value),'身份已切换')});
$('close-drawer').addEventListener('click',()=>$('drawer').close());$('drawer').addEventListener('click',e=>{if(e.target===$('drawer')){const r=$('drawer').getBoundingClientRect();if(e.clientX<r.left)$('drawer').close()}});
$('reset-demo').addEventListener('click',()=>$('confirm-dialog').showModal());$('cancel-reset').addEventListener('click',()=>$('confirm-dialog').close());$('confirm-reset').addEventListener('click',()=>{$('confirm-dialog').close();act(()=>HZ.actions.reset(),'已恢复示例数据')});
HZ.onChange=()=>{renderHome();if($('drawer').open)renderPanel()};renderHome();refreshIcons();
// The same room actions are available to browsers that support WebMCP.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const tools=[
  {name:'read_shared_home',title:'查看合租房',description:'Read the current browser-local demo room, roommates, bills, tasks, supplies and agreements.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(){return JSON.parse(JSON.stringify({current:HZ.state.current,summary:HZ.summary(),people:HZ.people,bills:HZ.state.bills,tasks:HZ.state.tasks,items:HZ.state.items,pacts:HZ.state.pacts}))}},
  {name:'open_home_space',title:'打开家中空间',description:'Open the room panel for bills, cleaning, supplies or roommate agreements without changing records.',inputSchema:{type:'object',properties:{space:{type:'string',enum:['bills','cleaning','items','pacts']}},required:['space'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!modules[input.space])throw Error('Unknown home space');openPanel(input.space);return {space:input.space,opened:true}}},
  {name:'switch_roommate',title:'切换室友身份',description:'Switch the demo to an existing roommate identity and update the visible home and panel.',inputSchema:{type:'object',properties:{personId:{type:'string',enum:HZ.people.map(p=>p.id)}},required:['personId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!HZ.person(input.personId))throw Error('Unknown roommate');formState=null;HZ.actions.selectPerson(input.personId);return {current:HZ.state.current,summary:HZ.summary()}}},
  {name:'create_shared_bill',title:'新建AA账单',description:'Create and save an equal-split shared bill in the local demo. Amount is an integer number of cents.',inputSchema:{type:'object',properties:{title:{type:'string',minLength:1,maxLength:60},totalCents:{type:'integer',minimum:1,maximum:100000000},payerId:{type:'string',enum:HZ.people.map(p=>p.id)},participantIds:{type:'array',items:{type:'string',enum:HZ.people.map(p=>p.id)},minItems:1,uniqueItems:true}},required:['title','totalCents','payerId','participantIds'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input)throw Error('Bill input required');const bill=HZ.actions.createBill({title:input.title,total:input.totalCents,payer:input.payerId,ids:input.participantIds});return {id:bill.id,title:bill.title,totalCents:bill.total,shares:bill.shares}}}
 ];
 for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
